# Generated by Django 5.0.1 on 2024-03-18 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема рассылки')),
                ('content', models.TextField(verbose_name='Содержание рассылки')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=25, verbose_name='Имя пользователя')),
                ('email', models.EmailField(default='Еще не заполнен', max_length=60, unique=True, verbose_name='Почта')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефона')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Админ'), ('JOURNALIST', 'Журналист')], max_length=200, null=True, verbose_name='Роль')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('OTHER', 'Другое')], max_length=20, null=True, verbose_name='Пол')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('otp_reset', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_reset_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('subscribed', models.BooleanField(default=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('newsletters', models.ManyToManyField(blank=True, to='account.newsletter', verbose_name='Полученные рассылки')),
            ],
            options={
                'verbose_name': 'Подписанные на рассылку',
                'verbose_name_plural': 'Подписанные на рассылку',
            },
        ),
    ]
