# Generated by Django 5.0.1 on 2024-02-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='category',
            new_name='categories',
        ),
    ]
