# Generated by Django 5.0.1 on 2024-02-04 13:05

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
