# Generated by Django 5.0.1 on 2024-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Админ'), ('JOURNALIST', 'Журналист')], max_length=200, null=True, verbose_name='Роль'),
        ),
    ]
