# Generated by Django 5.0.1 on 2024-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('МУЖСКОЙ', 'МУЖСКОЙ'), ('ЖЕНСКИЙ', 'ЖЕНСКИЙ')], max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
