# Generated by Django 5.0.1 on 2024-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=25, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
