# Generated by Django 5.0.1 on 2024-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема рассылки')),
                ('content', models.TextField(verbose_name='Содержание рассылки')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('newsletters', models.ManyToManyField(blank=True, to='account.newsletter', verbose_name='Полученные рассылки')),
            ],
            options={
                'verbose_name': 'Подписанные на рассылку',
                'verbose_name_plural': 'Подписанные на рассылку',
            },
        ),
    ]
