# Generated by Django 5.0.1 on 2024-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
