# Generated by Django 5.0.1 on 2024-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_subscriber_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
