# Generated by Django 5.0.1 on 2024-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photo_for_slider'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
