# Generated by Django 5.0.1 on 2024-02-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_author_news_count_likes_alter_news_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
