# Generated by Django 5.0.1 on 2024-01-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_news_author_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider'),
        ),
    ]
