# Generated by Django 5.0.1 on 2024-01-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
