# Generated by Django 5.0.1 on 2024-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photo_for_slider'),
        ),
    ]
