# Generated by Django 5.0.1 on 2024-01-31 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_news_count_likes_alter_news_photo_alter_slider_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ползователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='my_app.tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
