# Generated by Django 4.2.7 on 2024-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(default=1, upload_to='images/turism/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
