# Generated by Django 5.0.1 on 2024-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0004_category_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='caption',
            field=models.CharField(default=1, max_length=100, verbose_name='Надпись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.TextField(blank=True, null=True, verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_2',
            field=models.TextField(blank=True, null=True, verbose_name='Страница 2'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_3',
            field=models.TextField(blank=True, null=True, verbose_name='Страница 3'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_4',
            field=models.TextField(blank=True, null=True, verbose_name='Страница 4'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_5',
            field=models.TextField(blank=True, null=True, verbose_name='Страница 5'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_2',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_3',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_4',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_5',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок 5'),
            preserve_default=False,
        ),
    ]
