# Generated by Django 4.2.7 on 2024-01-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0004_placeimage_alter_place_image_delete_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='turism.place', verbose_name='Место'),
        ),
    ]
