# Generated by Django 5.0.1 on 2024-03-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='page_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='page_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='page_4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='page_5',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_5',
        ),
    ]
