# Generated by Django 4.2.7 on 2024-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0006_region_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='month_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='month',
        ),
        migrations.AddField(
            model_name='place',
            name='month',
            field=models.ManyToManyField(related_name='places', to='turism.month', verbose_name='Месяц'),
        ),
    ]
