# Generated by Django 5.0.1 on 2024-03-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0006_remove_category_page_2_remove_category_page_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='description_1',
            field=models.TextField(default=1, verbose_name='Описание 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='img_1',
            field=models.ImageField(default=1, upload_to='images/turism/', verbose_name='Фото 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='img_2',
            field=models.ImageField(default=1, upload_to='images/turism/', verbose_name='Фото 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='img_3',
            field=models.ImageField(default=1, upload_to='images/turism/', verbose_name='Фото 3'),
            preserve_default=False,
        ),
    ]
