# Generated by Django 4.2.7 on 2024-01-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0007_month_remove_place_month_place_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения места'},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='month',
            new_name='months',
        ),
    ]
