# Generated by Django 5.0.1 on 2024-03-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0007_region_description_1_region_img_1_region_img_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда бы вы хотели поехать?')),
                ('travel_month', models.CharField(blank=True, max_length=20, null=True, verbose_name='Когда вы хотели бы поехать? (Месяц)')),
                ('travel_year', models.IntegerField(blank=True, null=True, verbose_name='Когда вы хотели бы поехать? (Год)')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Надолго ли?')),
                ('num_travelers', models.IntegerField(blank=True, null=True, verbose_name='Сколько человек путешествует?')),
                ('budget_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сколько вы хотели бы потратить на одного человека?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Еще какие-нибудь комментарии или пожелания?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
    ]
