# Generated by Django 5.0.1 on 2024-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0008_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='description_1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 1'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='description_2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание 2'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='traveller',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Заголовок'),
        ),
    ]
