# Generated by Django 4.2.7 on 2024-01-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0008_alter_placeimage_options_rename_month_place_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/turism/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
            },
        ),
        migrations.AlterField(
            model_name='month',
            name='image',
            field=models.ImageField(upload_to='images/turism/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='place',
            name='traveller',
            field=models.ManyToManyField(related_name='places', to='turism.traveller', verbose_name='Путешествие'),
        ),
    ]
