# Generated by Django 5.0.1 on 2024-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0009_traveller_alter_month_image_place_traveller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('video_url', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео для заставки',
                'verbose_name_plural': 'Видео для заставки',
            },
        ),
    ]
