# Generated by Django 5.0.1 on 2024-01-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0010_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='videos/turism/', verbose_name='Видео'),
        ),
    ]
