# Generated by Django 5.0.1 on 2024-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0011_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',), 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
