# Generated by Django 5.0.1 on 2024-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0012_alter_region_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение'),
        ),
    ]
