# Generated by Django 5.0.1 on 2024-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turism', '0013_alter_month_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='months',
            field=models.ManyToManyField(blank=True, null=True, related_name='places', to='turism.month', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='place',
            name='traveller',
            field=models.ManyToManyField(blank=True, null=True, related_name='places', to='turism.traveller', verbose_name='Путешествие'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/turism/', verbose_name='Изображение'),
        ),
    ]
